version: '3'

services:

  backend:
    build: ./backend-app
#    image: node:7
    volumes:
      - ./backend-app:/app
    working_dir: /app
#    command: npm start
    command: echo Hello
    ports:
      - 3000:3000

  frontend:
    build: ./frontend-app
    volumes:
      - ./frontend-app:/app
    working_dir: /app
#    command: npm start
    command: echo Hello
    ports:
      - 4200:4200

  redis:
    image: redis

  redis.console:
    image: redis
    command: redis-cli -h redis
    links:
      - redis

  mongo:
    image: mongo

  mongo.console:
    image: mongo
    command: mongo --host mongo
    links:
      - mongo
